### ISSUE TITLE
PROXY as global in http.lua

### ISSUE THREAD

**Issue by svarogg** [lunarmodules/luasocket#110] opened 2014-11-03 09:38 UTC
Line 189 and 201 uses global variable PROXY. 
It breaks my tests as I am using a strict globals checker to make sure no globals were declared.
This was fixed 5 Jul 2013 in https://github.com/diegonehab/luasocket/commit/1f9ccb2b586c3a7e29db3c99a23ac1cee6907cf2 but the patch was not released as a rock yet.

Since latest release(v3.0-rc1) was quite some time ago - 14 Jun 2013, when can I expect a new release that fixes that issue?

**Comment by daurnimator** [comment] 2015-01-06 16:28
@diegonehab do you have time to review/merge the pull requests @catwell mentioned?

**Comment by jjvbsag** [comment] 2018-11-04 07:52
:+1: For now I have to patch all occurrences of http.lua I find (e.g. in ZeroBrane Studio). I'd prefer a released version with the fix

**Comment by diegonehab** [comment] 2018-11-04 17:13
Which one are you taking about? The HTTP proxy one 110? Although it is open, isn't the code merged anyway? The uClibc one (#90) has conflicts. If it is adjusted and tested, I can merge. I need someone to take charge of #81 and test it properly, as it seems to be a delicate change. #101 is not a big deal, and if somebody tests it I can also merge.

**Comment by diegonehab** [comment] 2018-11-05 21:10
@jjvbsag ?

**Comment by jjvbsag** [comment] 2018-11-06 05:46
Sorry, was busy on the job...
This is the patch, I'm talking about:
```diff
--- http.lua.orig	2018-11-03 10:54:52.997376028 +0100
+++ http.lua	2018-11-03 10:55:33.496561255 +0100
@@ -186,7 +186,7 @@
 local function adjusturi(reqt)
     local u = reqt
     -- if there is a proxy, we need the full url. otherwise, just a part.
-    if not reqt.proxy and not PROXY then
+    if not reqt.proxy and not _M.PROXY then
         u = {
            path = socket.try(reqt.path, "invalid path 'nil'"),
            params = reqt.params,
@@ -198,7 +198,7 @@
 end
 
 local function adjustproxy(reqt)
-    local proxy = reqt.proxy or PROXY
+    local proxy = reqt.proxy or _M.PROXY
     if proxy then
         proxy = url.parse(proxy)
         return proxy.host, proxy.port or 3128
```
See also pkulchenko/ZeroBraneStudio#950 for how to reproduce
(the second issue mentioned there is already fixed in your master)

---

About testing. For me it is all about a project on an ARM target. I am willing to try anything there, but as the project time line is extremely tight I can make no promises about when...

**Comment by ewestbrook** [comment] 2019-02-17 11:41
Will the tagging of a new release solve this problem?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!

**Comment by jjvbsag** [comment] 2019-02-17 11:48
Hi! Its in the master branch, so releasing a new tagged version seems fine for me...
Regards

**Comment by catwell** [comment] 2023-11-08 14:25
This issue has been fixed for a long time and a release has been shipped since then, closing.

**Closed by catwell** 2023-11-08 14:25 UTC
