### ISSUE TITLE
error compiling on windows 10 - mingw64

### ISSUE THREAD

**Issue by dwexel** [lunarmodules/luasocket#394] opened 2022-09-27 06:01 UTC
Hello, trying to install luasocket with `luarocks install luasocket` gives errors. I have both a 32-bit version and a 64-bit version of gcc, and interestingly, the 32-bit version successfully compiled `luarocks install lpeg` while the 64-bit version didn't. However, some people here seem to be using a 64-bit compiler with luarocks to install luasocket. Neither one works with installing luasocket, however.
gcc version 6.3.0

<img width="960" alt="Screenshot 2022-09-27 005438" src="https://user-images.githubusercontent.com/88518920/192444725-7c9613d3-ca98-44aa-959c-523236192c97.png">

Previously, I had issues trying to install rocks when luarocks would call "gcc" for some steps, and a different command, "mingw32-gcc" for another step, so I set the luarocks config to use "gcc" as the command for all the steps of the compiling process, and used the system PATH to point it to the 64-bit version or the 32-bit.

This method worked when installing lpeg, but not luasocket. Is this a problem with how I've set up luarocks? I'm not sure where to go from here. 
Thanks!

edit: this is the error when I use a 32-bit gcc:
<img width="960" alt="Screenshot 2022-09-27 011947" src="https://user-images.githubusercontent.com/88518920/192448194-aaecdb53-269f-4b6e-b3f2-44ee0f5d41ff.png">

**Comment by dwexel** [comment] 2022-09-27 06:25
I found similar issues in the "closed issues" section. I will keep looking there.

**Comment by dwexel** [comment] 2022-09-27 18:11
Update: seemed to work after using downloading and using the 32-bit version of winlibs as per https://github.com/lunarmodules/luasocket/issues/337#issuecomment-1197562163

I didn't want to have to get into trying the whole visual studio thing!

**Comment by hishamhm** [comment] 2022-12-08 19:32
I seem to have hit a similar error using mingw-w64 to cross-compile a Windows binary from a Linux host.

My solution was to download the rockspec locally and revert #383 manually (that is, to add the `LUASOCKET_INET_PTON` back to the `mingw32` section by uncommenting line 37 from [luarocks-3.1.0-1.rockspec](https://luarocks.org/manifests/lunarmodules/luasocket-3.1.0-1.rockspec)).

LuaRocks currently (as of 3.9.1) does not support different platform entries for `mingw32` and `mingw64`... I wonder if that's the proper solution. I'll run some local tests.

**Comment by hishamhm** [comment] 2022-12-08 19:39
> LuaRocks currently (as of 3.9.1) does not support different platform entries for mingw32 and mingw64... 

Apparently this is not enough, because mingw32-w64 also has a i686 target ("the 32-bit version of the 64-bit fork of mingw32"... are you confused yet?). I'm starting to wonder if this is less about the architecture and more about the version of mingw...

**Comment by alerque** [comment] 2023-11-10 20:03
Please don't post screen shots of terminal stuff, I can barely read this. Copy and paste please! It makes it both readable and searchable.

Also this seems to be a duplicate of #241 and *possibly* even fixed in the current release. Feel free to add more details to the original report if there are any.

**Closed by alerque** 2023-11-10 20:03 UTC
