### ISSUE TITLE
please update website

### ISSUE THREAD

**Issue by capr** [lunarmodules/luasocket#92] opened 2014-02-27 00:24 UTC
hi,

the docs at http://www.impa.br/~diego/software/luasocket are out of date.

one idea to avoid having to sync the site with github every time is to make it redirect to this url:

https://rawgithub.com/diegonehab/luasocket/master/doc/index.html

thanks.

**Comment by alerque** [comment] 2022-03-19 17:20
Yup yup. Very out of date. Documentation contributions welcome!

I'm closing this as  a duplicate of a newer issue (#357), but same idea...

**Closed by alerque** 2022-03-19 17:20 UTC
