### ISSUE TITLE
Compile error using MinGW-GCC in win10

### ISSUE THREAD

**Issue by xubury** [lunarmodules/luasocket#321] opened 2020-12-07 08:44 UTC
I try to install lusocket via luarocks. But it fail compiling. MinGW-GCC define `socklen_t` as `size_t`. Is MinGW compiler supported?
```
$ luarocks install luasocket
In file included from src/luasocket.c:30:
src/inet.h:46:13: error: conflicting types for 'inet_ntop'
   46 | const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt);
      |             ^~~~~~~~~
In file included from src/wsocket.h:12,
                 from src/socket.h:18,
                 from src/inet.h:18,
                 from src/luasocket.c:30:
C:/msys64/mingw64/x86_64-w64-mingw32/include/ws2tcpip.h:451:35: note: previous declaration of 'inet_ntop' was here
  451 | WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, LPCVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
      |                                   ^~~~~~~~~
In file included from src/luasocket.c:30:
src/inet.h:47:5: warning: 'inet_pton' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   47 | int inet_pton(int af, const char *src, void *dst);
      |     ^~~~~~~~~
Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock
gcc -O2 -fPIC -c -o src/mime.o -IC:/msys64/mingw64/include/lua5.1 src/mime.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
gcc -shared -o mime/core.dll src/mime.o C:/msys64/mingw64/lib/liblua5.1.dll.a -lm
gcc -O2 -fPIC -c -o src/luasocket.o -IC:/msys64/mingw64/include/lua5.1 src/luasocket.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)

Error: Build error: Failed compiling object src/luasocket.o
```

**Comment by KostyaCholak** [comment] 2021-04-02 10:31
Getting the same error

**Comment by KostyaCholak** [comment] 2021-04-02 11:13
Fixed by commenting line src/inet.h:46 as it redeclared inet_ntop from ws2tcpip.h, just as error says
- const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt);
+ // const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt);

Tried installing using luarocks at first, but after this error had to download sources, fix them and build manualy

**Comment by deb75** [comment] 2021-06-09 19:59
The issue is still there. It can be fixed by removing option `LUASOCKET_INET_PTON` compilation directive.

However, I run into the following errors : 
```
$ luarocks.lua make
src/luasocket.c: In function 'global_skip':
src/luasocket.c:67:18: warning: implicit declaration of function 'luaL_checkint'; did you mean 'luaL_checkany'? [-Wimplicit-function-declaration]
   67 |     int amount = luaL_checkint(L, 1);
      |                  ^~~~~~~~~~~~~
      |                  luaL_checkany
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o: in function `_CRT_INIT':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:130: undefined reference to `_execute_onexit_table'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o: in function `pre_c_init':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:64: undefined reference to `_initialize_onexit_table'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o: in function `atexit':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:206: undefined reference to `_register_onexit_function'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/luasocket.o:luasocket.c:(.text+0x20): undefined reference to `luaL_checkint'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/inet.o:inet.c:(.text+0x7ec): undefined reference to `gai_strerrorA'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/inet.o:inet.c:(.text+0x94c): undefined reference to `gai_strerrorA'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/udp.o:udp.c:(.text+0x7dc): undefined reference to `gai_strerrorA'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/udp.o:udp.c:(.text+0xab4): undefined reference to `gai_strerrorA'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/wsocket.o:wsocket.c:(.text+0xe81): undefined reference to `gai_strerrorA'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o): in function `__report_error':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:149: undefined reference to `__acrt_iob_func'
D:/utils/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:150: undefined reference to `__acrt_iob_func'
collect2.exe: error: ld returned 1 exit status

luasocket scm-0 depends on lua >= 5.1 (5.4-1 provided by VM)
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/luasocket.o -ID:/utils/msys64/mingw64/include src/luasocket.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/timeout.o -ID:/utils/msys64/mingw64/include src/timeout.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/buffer.o -ID:/utils/msys64/mingw64/include src/buffer.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/io.o -ID:/utils/msys64/mingw64/include src/io.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/auxiliar.o -ID:/utils/msys64/mingw64/include src/auxiliar.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/options.o -ID:/utils/msys64/mingw64/include src/options.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/inet.o -ID:/utils/msys64/mingw64/include src/inet.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/except.o -ID:/utils/msys64/mingw64/include src/except.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/select.o -ID:/utils/msys64/mingw64/include src/select.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/tcp.o -ID:/utils/msys64/mingw64/include src/tcp.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/udp.o -ID:/utils/msys64/mingw64/include src/udp.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -O2 -c -o src/wsocket.o -ID:/utils/msys64/mingw64/include src/wsocket.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport) -Ic:/windows/system32/include
D:\edebry\Documents\utils\msys64\mingw64\bin\gcc.exe -shared -o socket/core.dll src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/wsocket.o -Lc:/windows/system32 -lws2_32 D:/utils/msys64/mingw64/bin/lua54.dll -lm

Error: Build error: Failed compiling module socket/core.dll
```

**Comment by deb75** [comment] 2021-06-10 08:13
Hello,

It seems related to `msvcrt.dll` library.

I did check this laibrary is present on my path, but the version expected by mingw64 could be different from the one actually installed.

How do I check the library version ?

**Comment by ALENTL** [comment] 2022-07-09 12:39
> Fixed by commenting line src/inet.h:46 as it redeclared inet_ntop from ws2tcpip.h, just as error says `const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt);` -> `// const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt);`
> 
> Tried installing using luarocks at first, but after this error had to download sources, fix them and build manualy

How? Can you explain pls

**Comment by KostyaCholak** [comment] 2022-07-10 05:23
Not sure, but most likely it did it like this:
1. downloaded sources
2. commented the line
and then one of the two (I don't remember which one exactly):
3. run `make install` inside the sources folder
4. run `luarocks make luasocket/luasocket-scm-3.rockspec` outside of the sources folder. Where `luasocket/luasocket-scm-3.rockspec` is a path to a rockspec file

**Comment by ALENTL** [comment] 2022-07-10 07:45
> 

Can you tell where what all to set up here
![image](https://user-images.githubusercontent.com/82425585/178135958-4b41f5a8-478e-4c01-b730-1578d52bc57f.png)

My lua installation looks like
![image](https://user-images.githubusercontent.com/82425585/178135971-1a06c562-1503-4b76-92ff-7d1c661a5d09.png)

**Comment by goldenstein64** [comment] 2022-07-26 07:52
I'm using:

* PowerShell 7.2.5 from official site
* LuaRocks 3.9.1 from official site
* LuaJIT 2.0.5 from official site
* Windows 11 running on an x86_64 ISA
* GCC 11.2.0 (renamed to `mingw32-gcc.exe`) from [nuwen.net](https://nuwen.net/mingw.html)

Not sure if I'm missing any other specs...

These are the steps I took to install LuaSocket 3.0.0

1. Download the source.
2. In `rockspecs/luasocket-3.0.0-1.rockspec`, apply this diff either with `git apply` or manually.

```diff
diff --git a/rockspecs/luasocket-3.0.0-1.rockspec b/rockspecs/luasocket-3.0.0-1.rockspec
index 4cf4acf..8569764 100644
--- a/rockspecs/luasocket-3.0.0-1.rockspec
+++ b/rockspecs/luasocket-3.0.0-1.rockspec
@@ -34,7 +34,7 @@ local function make_plat(plat)
     },
     mingw32 = {
       "LUASOCKET_DEBUG",
-      "LUASOCKET_INET_PTON",
+      -- "LUASOCKET_INET_PTON",
       "WINVER=0x0501"
     }
   }
@@ -113,6 +113,7 @@ local function make_plat(plat)
   then
     modules["socket.core"].sources[#modules["socket.core"].sources+1] = "src/wsocket.c"
     modules["socket.core"].libraries = { "ws2_32" }
+    modules["socket.core"].libdirs = {}
   end
   return { modules = modules }
 end
```

* The removal of `"LUASOCKET_INET_PTON"` fixes the OP's issue. It seems that more recent versions of MinGW already have whatever this flag defines, see #298.
* The addition of the `libdirs` line fixes deb75's issue by removing `-Lc:/windows/system32` from the compilation of `socket/core.dll`. An educated guess is there exists a correctly defined `ws2_32` near my own version of GCC, but `system32` already has a different version of this file that's meant for something like MSVC, so it tries to use that and fails.

3. From the project's root directory, run `luarocks make rockspecs/luasocket-3.0.0-1.rockspec`. LuaSocket should now be installed.

**Comment by alerque** [comment] 2022-07-26 12:14
Thanks for pitching in that detailed information @goldenstein64.

I don't have access to anything Windows myself to test with, but it would be lovely if you could submit that diff as a PR. If we can get even one other confirmation from somebody that the patch works for them and I can test that it doesn't break for *nix platforms then I'm happy to apply it and get a release out so this doesn't keep tripping people up when a known fix exists.

**Comment by alerque** [comment] 2022-07-26 20:13
Hey @xubury, @KostyaCholak, @deb75, @ALENTL, or anybody else that has bumped into this issue on Windows...

Can somebody give @383 a shake and confirm it solves the issue for you? I can double check it didn't break anything else but I can't confirm Windows anything. This passes a smell test, but beyond that it would be really nice to have a second pair of eyes/expertise confirm this.

**Comment by ALENTL** [comment] 2022-07-26 20:15
> Hey @xubury, @KostyaCholak, @deb75, @ALENTL, or anybody else that has bumped into this issue on Windows...
> 
> Can somebody give #383 a shake and confirm it solves the issue for you? I can double check it didn't break anything else but I can't confirm Windows anything. This passes a smell test, but beyond that it would be really nice to have a second pair of eyes/expertise confirm this.

It just solved my issue
![image](https://user-images.githubusercontent.com/82425585/181103817-17e6d4f1-ae5e-4ba7-9da5-de1e2588fced.png)

**Closed** 2022-07-26 20:24 UTC

**Comment by ALENTL** [comment] 2022-10-11 06:58
Lemme try that. But which lua version where you using
